### ISSUE TITLE
LUL carriages aren't available until 1960, but LUL stock starts in 1938

### ISSUE THREAD

**Issue by mallardtheduck** [StarRaid/Representitive-UK-Trainset#3]
This means that LUL 1938 stock can only be run in "motor pairs" for 22 years. Looks like the carriages introduction date wasn't updated when the 1938 stock was added.

**Comment by StarRaid** [comment]
Cheers for taking note of that! I will get that fixed for a future bug fix. Sadly I doubt that will be released for a while though.
